CREATE table user (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  date_birth timestamp NOT NULL,
  first_name varchar NOT NULL,
  last_name varchar NOT NULL,
  mail varchar UNIQUE NOT NULL,
  password varchar NOT NULL,
  phone varchar NOT NULL,
  country varchar NOT NULL,
  created_at timestamp NOT NULL,
  updated_at timestamp,
  deleted_at timestamp
);

CREATE TABLE reservation (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_offer int NOT NULL,
  id_user int NOT NULL,
  created_at timestamp NOT NULL,
  updated_at timestamp,
  id_status int NOT NULL,
  payment_details int NOT NULL
);

CREATE TABLE reservation_status (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  status varchar UNIQUE NOT NULL
);

CREATE TABLE agencie (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name varchar UNIQUE NOT NULL,
  country varchar NOT NULL,
  city varchar NOT NULL,
  address varchar NOT NULL,
  phone varchar NOT NULL
);

CREATE TABLE "payment" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "created_at" timestamp NOT NULL,
  "id_reservation" int NOT NULL,
  "status" varchar NOT NULL,
  "transaction" varchar UNIQUE NOT NULL,
  "info" varchar
);

CREATE TABLE offer (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_agencie int NOT NULL,
  departure_city varchar NOT NULL,
  return_city varchar NOT NULL,
  departure_date_time timestamp NOT NULL,
  return_date_time timestamp NOT NULL,
  id_vehicle int NOT NULL,
  price decimal NOT NULL,
  discount decimal
);

CREATE TABLE vehicle_categorie (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name varchar NOT NULL,
  code varchar NOT NULL
);

CREATE TABLE vehicle_type (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name varchar NOT NULL,
  code varchar NOT NULL
);

CREATE TABLE vehicle_transmission_drive (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name varchar NOT NULL,
  code varchar NOT NULL
);

CREATE TABLE vehicle_fuel_air_cond (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name varchar NOT NULL,
  code varchar NOT NULL
);

CREATE TABLE vehicle (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name varchar NOT NULL,
  id_agencie int NOT NULL,
  id_vehicle_categorie int NOT NULL,
  id_vehicle_type int NOT NULL,
  id_vehicle_transmission_drive int NOT NULL,
  id_vehicle_fuel_air_cond int NOT NULL,
  id_status int NOT NULL,
  tarif_basic decimal NOT NULL
);

CREATE TABLE vehicle_status (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  status varchar NOT NULL
);

CREATE TABLE chat_session (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_user int NOT NULL,
  id_user_staf int NOT NULL,
  created_at timestamp NOT NULL
);

CREATE TABLE notification (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_user int NOT NULL,
  id_reservation int NOT NULL,
  created_at timestamp NOT NULL,
  status varchar NOT NULL,
  text varchar NOT NULL
);

CREATE TABLE chat_message (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_session int NOT NULL,
  id_user int NOT NULL,
  message_text varchar NOT NULL,
  created_at timestamp NOT NULL,
  file varchar
);

ALTER TABLE "user" ADD FOREIGN KEY ("id") REFERENCES "reservation" ("id_user");

ALTER TABLE "reservation_status" ADD FOREIGN KEY ("id") REFERENCES "reservation" ("id_status");

ALTER TABLE "offer" ADD FOREIGN KEY ("id_agencie") REFERENCES "agencie" ("id");

ALTER TABLE "vehicle" ADD FOREIGN KEY ("id") REFERENCES "offer" ("id_vehicle");

ALTER TABLE "agencie" ADD FOREIGN KEY ("id") REFERENCES "vehicle" ("id_agencie");

ALTER TABLE "vehicle_categorie" ADD FOREIGN KEY ("id") REFERENCES "vehicle" ("id_vehicle_categorie");

ALTER TABLE "vehicle_status" ADD FOREIGN KEY ("id") REFERENCES "vehicle" ("id_status");

ALTER TABLE "user" ADD FOREIGN KEY ("id") REFERENCES "chat_session" ("id_user");

ALTER TABLE "user" ADD FOREIGN KEY ("id") REFERENCES "chat_session" ("id_user_staf");

ALTER TABLE "offer" ADD FOREIGN KEY ("id") REFERENCES "reservation" ("id_offer");

ALTER TABLE "chat_session" ADD FOREIGN KEY ("id") REFERENCES "chat_message" ("id_session");

ALTER TABLE "user" ADD FOREIGN KEY ("id") REFERENCES "chat_message" ("id_user");

ALTER TABLE "vehicle_transmission_drive" ADD FOREIGN KEY ("id") REFERENCES "vehicle" ("id_vehicle_transmission_drive");

ALTER TABLE "vehicle_type" ADD FOREIGN KEY ("id") REFERENCES "vehicle" ("id_vehicle_type");

ALTER TABLE "vehicle_fuel_air_cond" ADD FOREIGN KEY ("id") REFERENCES "vehicle" ("id_vehicle_fuel_air_cond");

ALTER TABLE "reservation" ADD FOREIGN KEY ("payment_details") REFERENCES "payment" ("id");

ALTER TABLE "reservation" ADD FOREIGN KEY ("id") REFERENCES "payment" ("id_reservation");

ALTER TABLE "user" ADD FOREIGN KEY ("id") REFERENCES "notification" ("id_user");

ALTER TABLE "reservation" ADD FOREIGN KEY ("id") REFERENCES "notification" ("id_reservation");
